name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build-and-release:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Set release date
        id: release_date
        run: |
          # UTC timestamp: YYYYMMDD-HHMMSS
          echo "date=$(date -u +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.release_date.outputs.date }}
          name: Release ${{ steps.release_date.outputs.date }}
          body: Automated release from CI
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}